name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: |
          dumpiff
          makesp2
          modeltool
